## <strong> 10. 시계열 데이터 생성 및 조작 </strong>

### <strong> Python 내장 모듈을 이용한 Datetime 생성
---

#### ```datetime```, ```dateutil```: 시계열 처리를 위한 Python 내장 모듈

In [2]:
from datetime import datetime

# datetime 객체 생성
t = datetime(year=2025, month=5, day=7)
t

datetime.datetime(2025, 5, 7, 0, 0)

In [3]:
type(t)

datetime.datetime

In [4]:
# datetime 속성 접근: year
t.year

2025

In [7]:
# 문자열 파싱을 통한 날짜 해석
from dateutil import parser
# 2024-11-05, 11-05, 2024
date = parser.parse("28th of April, 2026")
# date = parser.parse("05-07-2025")

date

datetime.datetime(2026, 4, 28, 0, 0)

#### ```strftime()```: datetime의 속성을 문자열 형태로 출력

In [9]:
# [+] 요일 출력
date.strftime('%A')

'Tuesday'

In [10]:
# [+] 월 출력
date.strftime('%B')

'April'

### <strong> NumPy를 이용한 Datetime 배열 생성</strong>
---
```datetime64```: ```NumPy```에서 지원하는 datetime 클래스

In [11]:
import numpy as np

# datetime64 배열 객체 생성
dates = np.array(['2025-05-07', '2025-05-08'], dtype=np.datetime64)
dates

array(['2025-05-07', '2025-05-08'], dtype='datetime64[D]')

In [14]:
# datetime64() 메서드를 이용한 객체 생성
date = np.datetime64('2025-05-01')
date

np.datetime64('2025-05-01')

In [22]:
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [13]:
# 벡터화 연산을 통한 Datetime 배열 생성
date + np.arange(31) # [0, 1, .. 30]

array(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
       '2025-05-05', '2025-05-06', '2025-05-07', '2025-05-08',
       '2025-05-09', '2025-05-10', '2025-05-11', '2025-05-12',
       '2025-05-13', '2025-05-14', '2025-05-15', '2025-05-16',
       '2025-05-17', '2025-05-18', '2025-05-19', '2025-05-20',
       '2025-05-21', '2025-05-22', '2025-05-23', '2025-05-24',
       '2025-05-25', '2025-05-26', '2025-05-27', '2025-05-28',
       '2025-05-29', '2025-05-30', '2025-05-31'], dtype='datetime64[D]')

In [23]:
# 분(minute) 단위의 Datetime 객체 생성
t = np.datetime64('2025-05-07 14:30')
t

np.datetime64('2025-05-07T14:30')

In [24]:
# 디폴트 시간 빈도: ms
t = np.datetime64('2025-05-07 14:30:59.99')
t

np.datetime64('2025-05-07T14:30:59.990')

In [25]:
# 시간 빈도를 Nanosecond로 설정
t = np.datetime64('2025-05-07 14:30:59.99', 'ns')
t

np.datetime64('2025-05-07T14:30:59.990000000')

In [26]:
# datetime64 코드: Y, M, D, h...
t = np.datetime64('2025-05-07 14:30:59.99', 'M')
t

np.datetime64('2025-05')

### <strong> Pandas에서의 시계열 처리</strong>
---

In [27]:
import pandas as pd

# [+] to_datetime() 함수를 이용한 Timestamp 객체 생성 
date = pd.to_datetime("2005-07-23") # 본인 생일로 입력
date

Timestamp('2005-07-23 00:00:00')

In [30]:
# [+] 요일 출력
date.strftime('%A')

'Saturday'

In [31]:
# NumPy 스타일의 배열 연산
date + pd.to_timedelta(np.arange(7))

DatetimeIndex([          '2005-07-23 00:00:00',
               '2005-07-23 00:00:00.000000001',
               '2005-07-23 00:00:00.000000002',
               '2005-07-23 00:00:00.000000003',
               '2005-07-23 00:00:00.000000004',
               '2005-07-23 00:00:00.000000005',
               '2005-07-23 00:00:00.000000006'],
              dtype='datetime64[ns]', freq=None)

In [32]:
date + pd.to_timedelta(np.arange(7), unit='D')

DatetimeIndex(['2005-07-23', '2005-07-24', '2005-07-25', '2005-07-26',
               '2005-07-27', '2005-07-28', '2005-07-29'],
              dtype='datetime64[us]', freq=None)

#### <strong> 시계열 생성

In [34]:
# DatetimeIndex 객체 생성
ind = pd.DatetimeIndex(['2022-10-27', '2022-10-28', '2022-10-29', '2022-10-30',
                        '2022-10-31', '2022-11-01', '2022-11-02'])
ind

DatetimeIndex(['2022-10-27', '2022-10-28', '2022-10-29', '2022-10-30',
               '2022-10-31', '2022-11-01', '2022-11-02'],
              dtype='datetime64[us]', freq=None)

In [36]:
pd.Series([0, 1, 2, 3, 4, 5, 6])

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [35]:
# [+] 시계열 인덱싱 적용
ser = pd.Series([0, 1, 2, 3, 4, 5, 6], index=ind)
ser

2022-10-27    0
2022-10-28    1
2022-10-29    2
2022-10-30    3
2022-10-31    4
2022-11-01    5
2022-11-02    6
dtype: int64

In [ ]:
ser.index

In [37]:
# [+] 인덱싱
ser['2022-10-30']

np.int64(3)

In [38]:
# [+] 슬라이싱
ser['2022-10-28':'2022-11-01']

2022-10-28    1
2022-10-29    2
2022-10-30    3
2022-10-31    4
2022-11-01    5
dtype: int64

In [41]:
# [+] 데이터 선택 
ser['2022-10']

2022-10-27    0
2022-10-28    1
2022-10-29    2
2022-10-30    3
2022-10-31    4
dtype: int64

In [42]:
ser['2022']

2022-10-27    0
2022-10-28    1
2022-10-29    2
2022-10-30    3
2022-10-31    4
2022-11-01    5
2022-11-02    6
dtype: int64

#### <strong>시계열 생성: 데이터셋의 타임스탬프 변수를 인덱스로 설정하기</strong>

In [43]:
path = "./data/"
filename = "AirQualityUCI_refined.csv"

df = pd.read_csv(path + filename)
df.head()

,Datetime,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT)
0,2004-03-10 18:00:00,2.6,1360.0,1046.0,166.0,1056.0,113.0,1692.0,1268.0,48.9,0.7578,11.9
1,2004-03-10 19:00:00,2.0,1292.0,955.0,103.0,1174.0,92.0,1559.0,972.0,47.7,0.7255,9.4
2,2004-03-10 20:00:00,2.2,1402.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,54.0,0.7502,9.0
3,2004-03-10 21:00:00,2.2,1376.0,948.0,172.0,1092.0,122.0,1584.0,1203.0,60.0,0.7867,9.2
4,2004-03-10 22:00:00,1.6,1272.0,836.0,131.0,1205.0,116.0,1490.0,1110.0,59.6,0.7888,6.5

<strong>방법 1: </strong>DataFrame.set_index()

In [55]:
df.set_index('Datetime', inplace=True) # 특정 컬럼을 인덱스로 설정, inplace=True: 원본객체 변경
df['2004-03':'2004-12']

<strong>방법 2: </strong>Pandas.read_csv(index_col=...)

In [44]:
df = pd.read_csv(path + filename, index_col='Datetime')
df.head()

,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT)
Datetime,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,1046.0,166.0,1056.0,113.0,1692.0,1268.0,48.9,0.7578,11.9
2004-03-10 19:00:00,2.0,1292.0,955.0,103.0,1174.0,92.0,1559.0,972.0,47.7,0.7255,9.4
2004-03-10 20:00:00,2.2,1402.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,54.0,0.7502,9.0
2004-03-10 21:00:00,2.2,1376.0,948.0,172.0,1092.0,122.0,1584.0,1203.0,60.0,0.7867,9.2
2004-03-10 22:00:00,1.6,1272.0,836.0,131.0,1205.0,116.0,1490.0,1110.0,59.6,0.7888,6.5

#### <strong> 시계열 관련 Pandas의 데이터 구조

In [46]:
# Timestamp와 DatetimeIndex
dates = pd.to_datetime([datetime(2015, 7, 3),
                      "4th of July, 2015",
                      '2015-Jul-6',
                      '07-07-2015',
                      '20150708'])
print(dates)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[us]', freq=None)

In [47]:
# to_period(): DatetimeIndex -> PeriodIndex 변환
dates.to_period('D')

PeriodIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
             '2015-07-08'],
            dtype='period[D]')

In [48]:
# to_period(): DatetimeIndex -> PeriodIndex 변환
dates.to_period('W')

PeriodIndex(['2015-06-29/2015-07-05', '2015-06-29/2015-07-05',
             '2015-07-06/2015-07-12', '2015-07-06/2015-07-12',
             '2015-07-06/2015-07-12'],
            dtype='period[W-SUN]')

In [62]:
# [+] TimedeltaIndex 생성
pd.timedelta_range(0, periods=10, freq='h') # 수업시간에 놓쳤어요

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='h')

#### <strong> 정규 시퀀스 </strong>

In [51]:
# [+] pd.date_range()를 이용한 정규 시퀀스 생성
pd.date_range('2026-01-01', '2026-04-28')

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10',
               ...
               '2026-04-19', '2026-04-20', '2026-04-21', '2026-04-22',
               '2026-04-23', '2026-04-24', '2026-04-25', '2026-04-26',
               '2026-04-27', '2026-04-28'],
              dtype='datetime64[us]', length=118, freq='D')

In [52]:
# [+] Period 값을 이용
pd.date_range('2026-04-28', periods=100)

DatetimeIndex(['2026-04-28', '2026-04-29', '2026-04-30', '2026-05-01',
               '2026-05-02', '2026-05-03', '2026-05-04', '2026-05-05',
               '2026-05-06', '2026-05-07', '2026-05-08', '2026-05-09',
               '2026-05-10', '2026-05-11', '2026-05-12', '2026-05-13',
               '2026-05-14', '2026-05-15', '2026-05-16', '2026-05-17',
               '2026-05-18', '2026-05-19', '2026-05-20', '2026-05-21',
               '2026-05-22', '2026-05-23', '2026-05-24', '2026-05-25',
               '2026-05-26', '2026-05-27', '2026-05-28', '2026-05-29',
               '2026-05-30', '2026-05-31', '2026-06-01', '2026-06-02',
               '2026-06-03', '2026-06-04', '2026-06-05', '2026-06-06',
               '2026-06-07', '2026-06-08', '2026-06-09', '2026-06-10',
               '2026-06-11', '2026-06-12', '2026-06-13', '2026-06-14',
               '2026-06-15', '2026-06-16', '2026-06-17', '2026-06-18',
               '2026-06-19', '2026-06-20', '2026-06-21', '2026-06-22',
               '2026-06-23', '2026-06-24', '2026-06-25', '2026-06-26',
               '2026-06-27', '2026-06-28', '2026-06-29', '2026-06-30',
               '2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04',
               '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08',
               '2026-07-09', '2026-07-10', '2026-07-11', '2026-07-12',
               '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16',
               '2026-07-17', '2026-07-18', '2026-07-19', '2026-07-20',
               '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
               '2026-07-25', '2026-07-26', '2026-07-27', '2026-07-28',
               '2026-07-29', '2026-07-30', '2026-07-31', '2026-08-01',
               '2026-08-02', '2026-08-03', '2026-08-04', '2026-08-05'],
              dtype='datetime64[us]', freq='D')

In [56]:
# 빈도 변경
#pd.date_range('2022-10-27', periods=12, freq='H') #표준 변경 H -> h
pd.date_range('2022-10-27', periods=12, freq='h')

DatetimeIndex(['2022-10-27 00:00:00', '2022-10-27 01:00:00',
               '2022-10-27 02:00:00', '2022-10-27 03:00:00',
               '2022-10-27 04:00:00', '2022-10-27 05:00:00',
               '2022-10-27 06:00:00', '2022-10-27 07:00:00',
               '2022-10-27 08:00:00', '2022-10-27 09:00:00',
               '2022-10-27 10:00:00', '2022-10-27 11:00:00'],
              dtype='datetime64[us]', freq='h')

In [59]:
# pd.period_range()
pd.period_range('2015-07', periods=8, freq='M')

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]')

In [60]:
# Timestamp vs. Period
period = pd.Period('2022-10-27')
timestamp = pd.Timestamp('2022-10-27 09:30')

print(period.start_time < timestamp < period.end_time)

print(period.start_time)

print(period.end_time)

True
2022-10-27 00:00:00
2022-10-27 23:59:59.999999

In [63]:
# pd.timedelta_range()
pd.timedelta_range(0, periods=10, freq='h') # 표준 변경 H->h

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='h')

| Code   | Description         | Code   | Description          |
|--------|---------------------|--------|----------------------|
| ``D``  | Calendar day        | ``B``  | Business day         |
| ``W``  | Weekly              |   -    |                      |
| ``M``  | Month end           | ``BM`` | Business month end   |
| ``Q``  | Quarter end         | ``BQ`` | Business quarter end |
| ``A``  | Year end            | ``BA`` | Business year end    |
| ``H``  | Hours               | ``BH`` | Business hours       |
| ``T``  | Minutes             |   -    |                      |
| ``S``  | Seconds             |   -    |                      |
| ``L``  | Milliseonds         |   -    |                      |
| ``U``  | Microseconds        |   -    |                      |
| ``N``  | nanoseconds         |   -    |                      |

#### <strong> 빈도 및 오프셋

In [65]:
# 빈도 코드
pd.date_range('2022-11-01', periods=10, freq='h') #표준변경 H->h

DatetimeIndex(['2022-11-01 00:00:00', '2022-11-01 01:00:00',
               '2022-11-01 02:00:00', '2022-11-01 03:00:00',
               '2022-11-01 04:00:00', '2022-11-01 05:00:00',
               '2022-11-01 06:00:00', '2022-11-01 07:00:00',
               '2022-11-01 08:00:00', '2022-11-01 09:00:00'],
              dtype='datetime64[us]', freq='h')

In [70]:
# 빈도, M: 월말
(pd.date_range('2022-11-01', periods=10, freq="ME")) #표준 변경 M-> ME

DatetimeIndex(['2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28',
               '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30',
               '2023-07-31', '2023-08-31'],
              dtype='datetime64[us]', freq='ME')

In [73]:
# 빈도, BM: 비즈니스 기준 월말
pd.date_range('2022-11-01', periods=10, freq="BME") #표준 변경 BM -> BME

DatetimeIndex(['2022-11-30', '2022-12-30', '2023-01-31', '2023-02-28',
               '2023-03-31', '2023-04-28', '2023-05-31', '2023-06-30',
               '2023-07-31', '2023-08-31'],
              dtype='datetime64[us]', freq='BME')

In [74]:
# 접미사 'S': 시작 일시를 기준으로 시퀀스 생성
pd.date_range('2022-11-01', periods=10, freq='MS')

DatetimeIndex(['2022-11-01', '2022-12-01', '2023-01-01', '2023-02-01',
               '2023-03-01', '2023-04-01', '2023-05-01', '2023-06-01',
               '2023-07-01', '2023-08-01'],
              dtype='datetime64[us]', freq='MS')

In [84]:
# 빈도 코드 조합
pd.date_range('2026-04-28 09:30:00', periods=9, freq='1h30min') #2H30T -> 2h30min or 2h30s

DatetimeIndex(['2026-04-28 09:30:00', '2026-04-28 11:00:00',
               '2026-04-28 12:30:00', '2026-04-28 14:00:00',
               '2026-04-28 15:30:00', '2026-04-28 17:00:00',
               '2026-04-28 18:30:00', '2026-04-28 20:00:00',
               '2026-04-28 21:30:00'],
              dtype='datetime64[us]', freq='90min')

In [85]:
# 오프셋
from pandas.tseries.offsets import DateOffset
ts = pd.Timestamp('2023-11-07 09:30:00')
ts + DateOffset(hours=-40)

Timestamp('2023-11-05 17:30:00')

In [87]:
# 오프셋(minus)
ts - DateOffset(years=73, months=4, days=12, hours=5, minutes=10, seconds=00)

Timestamp('1950-06-25 04:20:00')